format: yamanifest
version: 1.0
---
work/atmosphere/um_hg3.exe:
  fullpath: /g/data/vk83/apps/spack/0.22/restricted/ukmo/release/linux-rocky8-x86_64_v4/intel-19.0.3.199/um7-git.2024.10.17_access-esm1.5-heooehpezvblo6woeptrz4gkge5qv3uv/bin/um_hg3.exe
  hashes:
    binhash: 50381bc82c482ae9b89f1b7ed923756b
    md5: b3a8c05213ff7a7ea884226e2f75b7cd
