format: yamanifest
version: 1.0
---
work/atmosphere/um_hg3.exe:
  fullpath: /g/data/vk83/apps/spack/0.22/restricted/ukmo/release/linux-rocky8-x86_64_v4/intel-19.0.3.199/um7-git.2024.10.17_access-esm1.5-l3w5m5ub4qkaai4rqsrixyeggwvenqeg/bin/um_hg3.exe
  hashes:
    binhash: 7d84592b11262545ecbe8a9d10f69055
    md5: 93c8bca8d07dd29b94e0a62ffc31c4f6
