format: yamanifest
version: 1.0
---
work/atmosphere/INPUT/BC_hi_1850_ESM1.anc:
  fullpath: /g/data/access/payu/access-esm/input/pre-industrial/atmosphere/BC_hi_1850_ESM1.anc
  hashes:
    binhash: 701eb25da0f3c9b0a430da1b51449a0a
    md5: 74803eb36a358f9ac8ecdae36cdb7f56
work/atmosphere/INPUT/Bio_1850_ESM1.anc:
  fullpath: /g/data/access/payu/access-esm/input/pre-industrial/atmosphere/Bio_1850_ESM1.anc
  hashes:
    binhash: bc0648b654c77fd6ec194f0ebc5ee489
    md5: 69dc6afb4bc7524d346f3b82f2657c97
work/atmosphere/INPUT/CABLE-AUX-1.4/core/biogeochem/modis_phenology_csiro.txt:
  fullpath: /g/data/access/payu/access-esm/input/pre-industrial/atmosphere/CABLE-AUX-1.4/core/biogeochem/modis_phenology_csiro.txt
  hashes:
    binhash: 29a05874c8b52806ec4273e04df58e62
    md5: a7b89d25cff82cf13cf812a98ad3a029
work/atmosphere/INPUT/CABLE-AUX-1.4/core/biogeochem/pftlookup_csiro_v16_17tiles.csv:
  fullpath: /g/data/access/payu/access-esm/input/pre-industrial/atmosphere/CABLE-AUX-1.4/core/biogeochem/pftlookup_csiro_v16_17tiles.csv
  hashes:
    binhash: 25dbaecf930f7f09243984e1f247a4a2
    md5: 8a0fd917ed5f20bb055decef119d394e
work/atmosphere/INPUT/CABLE-AUX-1.4/core/biogeochem/pftlookup_csiro_v16_17tiles_spinup.csv:
  fullpath: /g/data/access/payu/access-esm/input/pre-industrial/atmosphere/CABLE-AUX-1.4/core/biogeochem/pftlookup_csiro_v16_17tiles_spinup.csv
  hashes:
    binhash: cc36f541c3cfa76bd1ca1767441878d1
    md5: 043997298518f6d819f49634e8948be4
work/atmosphere/INPUT/CABLE-AUX-1.4/core/biogeochem/pftlookup_csiro_v16_17tiles_wtlnds.csv:
  fullpath: /g/data/access/payu/access-esm/input/pre-industrial/atmosphere/CABLE-AUX-1.4/core/biogeochem/pftlookup_csiro_v16_17tiles_wtlnds.csv
  hashes:
    binhash: d5dcc7c9459d4d9080733782abbab4af
    md5: a526e6d3a2ad2e24d069a3b9a572def7
work/atmosphere/INPUT/CABLE-AUX-1.4/core/biogeochem/poolcnpInTumbarumba.csv:
  fullpath: /g/data/access/payu/access-esm/input/pre-industrial/atmosphere/CABLE-AUX-1.4/core/biogeochem/poolcnpInTumbarumba.csv
  hashes:
    binhash: 94ffafc2c12869e0c89c6d7933b932d1
    md5: 6a4ee7bbb2e7bd074be9d036bf40d9e2
work/atmosphere/INPUT/CABLE-AUX-1.4/core/biogeophys/def_soil_params.txt:
  fullpath: /g/data/access/payu/access-esm/input/pre-industrial/atmosphere/CABLE-AUX-1.4/core/biogeophys/def_soil_params.txt
  hashes:
    binhash: 72cff3be9be9a986ec2a530732e5af39
    md5: 93107e8c37e04ccf97471fd2ac8f63eb
work/atmosphere/INPUT/CABLE-AUX-1.4/core/biogeophys/def_veg_params.txt:
  fullpath: /g/data/access/payu/access-esm/input/pre-industrial/atmosphere/CABLE-AUX-1.4/core/biogeophys/def_veg_params.txt
  hashes:
    binhash: 27a407dd57b0ceba94c9bbb2be3346b8
    md5: 1f9a27f0e252bf6c466100573c126789
work/atmosphere/INPUT/DMS_conc.N96:
  fullpath: /g/data/access/payu/access-esm/input/pre-industrial/atmosphere/DMS_conc.N96
  hashes:
    binhash: 56eda93e098dfefdef6d44a0bf06e958
    md5: 7e8ec8de832c0b9b8c1d9f0eda4d54e5
work/atmosphere/INPUT/Ndep_1850_ESM1.anc:
  fullpath: /g/data/access/payu/access-esm/input/pre-industrial/atmosphere/Ndep_1850_ESM1.anc
  hashes:
    binhash: 0eeb7a9a885bc51be3b28b546a8f6d2d
    md5: 48462cfa1aeed200c3b8d0bf1b49654a
work/atmosphere/INPUT/OCFF_1850_ESM1.anc:
  fullpath: /g/data/access/payu/access-esm/input/pre-industrial/atmosphere/OCFF_1850_ESM1.anc
  hashes:
    binhash: 2e48b826853e9ea77aa3e2571428770f
    md5: 95eec04860fa30ee863d30e67e683407
work/atmosphere/INPUT/SOURCES:
  fullpath: /g/data/access/payu/access-esm/input/pre-industrial/atmosphere/SOURCES
  hashes:
    binhash: 23f2d99ea24c4ae416249f6fd10f3a46
    md5: 5b3a5f40cb3a2ba0df1f3251e65194b6
work/atmosphere/INPUT/STASHmaster/STASHmaster_A:
  fullpath: /g/data/access/payu/access-esm/input/pre-industrial/atmosphere/STASHmaster/STASHmaster_A
  hashes:
    binhash: ac186e9b28d4ee478477d5e3532f9c85
    md5: 74cbbb76edfbd9f7c4b928609c00cd64
work/atmosphere/INPUT/STASHmaster/STASHmaster_A.original:
  fullpath: /g/data/access/payu/access-esm/input/pre-industrial/atmosphere/STASHmaster/STASHmaster_A.original
  hashes:
    binhash: fc8c2bab866aa0c4212fc553bba90485
    md5: ed1004d9aca8d29baba143ea12defbb7
work/atmosphere/INPUT/STASHmaster/STASHmaster_O:
  fullpath: /g/data/access/payu/access-esm/input/pre-industrial/atmosphere/STASHmaster/STASHmaster_O
  hashes:
    binhash: a372d2fa943fb85027b7dfba31c71642
    md5: 5a65d77c62d55e3b62e35ad9662d32a9
work/atmosphere/INPUT/STASHmaster/STASHmaster_S:
  fullpath: /g/data/access/payu/access-esm/input/pre-industrial/atmosphere/STASHmaster/STASHmaster_S
  hashes:
    binhash: d8e16218632dd3befe53a79bf7547072
    md5: 85ff5d563968cf24d1be595b05b4e52d
work/atmosphere/INPUT/STASHmaster/STASHmaster_W:
  fullpath: /g/data/access/payu/access-esm/input/pre-industrial/atmosphere/STASHmaster/STASHmaster_W
  hashes:
    binhash: 4b5c5ff64c2c06becea4b20f89bb2600
    md5: 1e4391ea1f6234b33c33168bd7089d06
work/atmosphere/INPUT/STASHmaster/STASHsections_A:
  fullpath: /g/data/access/payu/access-esm/input/pre-industrial/atmosphere/STASHmaster/STASHsections_A
  hashes:
    binhash: f714ff1636e91b87b4a6cb0083178ef8
    md5: 8525fd107dbea6184db74089f1d55fd9
work/atmosphere/INPUT/biogenic_351sm.N96L38:
  fullpath: /g/data/access/payu/access-esm/input/pre-industrial/atmosphere/biogenic_351sm.N96L38
  hashes:
    binhash: a807429d641a78a039eb70ba5bd5d83b
    md5: 55eb75f602a4639fb3c8ff40e36eb661
work/atmosphere/INPUT/cable_vegfunc_N96.anc:
  fullpath: /g/data/access/payu/access-esm/input/pre-industrial/atmosphere/cable_vegfunc_N96.anc
  hashes:
    binhash: 9cf1500dd7a40cea7ef044db06a4b60b
    md5: 7a8cb16191ad29b081514657893530c6
work/atmosphere/INPUT/ozone_1850_ESM1.anc:
  fullpath: /g/data/access/payu/access-esm/input/pre-industrial/atmosphere/ozone_1850_ESM1.anc
  hashes:
    binhash: d44cd5fe376e4e153623081280c51b4b
    md5: a64a01e3b092085fca308524a75a1cee
work/atmosphere/INPUT/qrclim.slt:
  fullpath: /g/data/access/payu/access-esm/input/pre-industrial/atmosphere/qrclim.slt
  hashes:
    binhash: 5c318ecae39e1378f5a7ada4300bacbf
    md5: dfb5e52b445917514e5c6ce2ac208c46
work/atmosphere/INPUT/qrclim.smow:
  fullpath: /g/data/access/payu/access-esm/input/pre-industrial/atmosphere/qrclim.smow
  hashes:
    binhash: 89d726f96d65a5e8521aa5f99162fd38
    md5: 89d4912892b8ebd22329dd131d326ccc
work/atmosphere/INPUT/qrparm.mask:
  fullpath: /g/data/access/payu/access-esm/input/pre-industrial/atmosphere/qrparm.mask
  hashes:
    binhash: a22afcd1049c436678fc4141444c78af
    md5: f497c7827bd22ef0b98f1d1af776866d
work/atmosphere/INPUT/qrparm.soil_igbp_vg:
  fullpath: /g/data/access/payu/access-esm/input/pre-industrial/atmosphere/qrparm.soil_igbp_vg
  hashes:
    binhash: 05814fc5223ef02de546fbee4e3efd1e
    md5: 26ce57f462dd574fe49f290ab7877112
work/atmosphere/INPUT/scycl_1850_ESM1_v4.anc:
  fullpath: /g/data/access/payu/access-esm/input/pre-industrial/atmosphere/scycl_1850_ESM1_v4.anc
  hashes:
    binhash: bbd36c569e37ce440db4b9730ae9aa87
    md5: 2c390f44c4f57078340cfbd408fdc754
work/atmosphere/INPUT/spec3a_lw_hadgem1_6on:
  fullpath: /g/data/access/payu/access-esm/input/pre-industrial/atmosphere/spec3a_lw_hadgem1_6on
  hashes:
    binhash: 6ee819e5786ee14f09abd3132d2063f6
    md5: 9ff85916dbb36ba6679b954d16387aee
work/atmosphere/INPUT/spec3a_sw_hadgem1_6on:
  fullpath: /g/data/access/payu/access-esm/input/pre-industrial/atmosphere/spec3a_sw_hadgem1_6on
  hashes:
    binhash: 39915c6c90e4df40fb0a716deec55249
    md5: 0e74c13cf3333132f38d8c5c52e1c7eb
work/atmosphere/INPUT/stasets/X01001218:
  fullpath: /g/data/access/payu/access-esm/input/pre-industrial/atmosphere/stasets/X01001218
  hashes:
    binhash: 1db5f5eaa1ab9031fc60a9742f6dc786
    md5: 7293caa27798d235bd5520eede9700fb
work/atmosphere/INPUT/stasets/X01002207:
  fullpath: /g/data/access/payu/access-esm/input/pre-industrial/atmosphere/stasets/X01002207
  hashes:
    binhash: fa4dd82bb4fd4f24f365bc085bffefcc
    md5: 448daeebba685950d0c347d0493b5fc4
work/atmosphere/INPUT/stasets/X01003236:
  fullpath: /g/data/access/payu/access-esm/input/pre-industrial/atmosphere/stasets/X01003236
  hashes:
    binhash: 59b02f84687c3edb381992a7b7af8a4e
    md5: 71a2288ee0a7d0fc89dafe95653c128a
work/atmosphere/INPUT/stasets/X01003237:
  fullpath: /g/data/access/payu/access-esm/input/pre-industrial/atmosphere/stasets/X01003237
  hashes:
    binhash: 84863390648c70d1360358170c53ef32
    md5: 4efd39ac9a917525bbc35146d6770e3b
work/atmosphere/INPUT/stasets/X01003254:
  fullpath: /g/data/access/payu/access-esm/input/pre-industrial/atmosphere/stasets/X01003254
  hashes:
    binhash: 092893a6e38ab9444bec295a698d2e77
    md5: 1b5f7755f752c2ee2086ac6eba886ca3
work/atmosphere/INPUT/stasets/X01003255:
  fullpath: /g/data/access/payu/access-esm/input/pre-industrial/atmosphere/stasets/X01003255
  hashes:
    binhash: 53c751c78cdb9787e8c6d3b69d1d2701
    md5: f23a78b048f0cb52ed0e2beb57f00fa8
work/atmosphere/INPUT/stasets/X01003274:
  fullpath: /g/data/access/payu/access-esm/input/pre-industrial/atmosphere/stasets/X01003274
  hashes:
    binhash: 179e605ff71ca5cebaa2464339841eb9
    md5: 032190f23c926eb47199da6e1f054bf1
work/atmosphere/INPUT/stasets/X01003275:
  fullpath: /g/data/access/payu/access-esm/input/pre-industrial/atmosphere/stasets/X01003275
  hashes:
    binhash: fd74988066a6923977793f5ff3db291b
    md5: 120694f3d078b9ade033b56217e9ed85
work/atmosphere/INPUT/stasets/X01003276:
  fullpath: /g/data/access/payu/access-esm/input/pre-industrial/atmosphere/stasets/X01003276
  hashes:
    binhash: 1b5620001d4698e4b2cc89acfdf68d4d
    md5: 61afb6eb4e76efb2171c56d02742e9ad
work/atmosphere/INPUT/stasets/X01003277:
  fullpath: /g/data/access/payu/access-esm/input/pre-industrial/atmosphere/stasets/X01003277
  hashes:
    binhash: 057139598531a1504822a8e751cc3fe2
    md5: d8cced93214dd8e84c0c9d06259412ab
work/atmosphere/INPUT/stasets/X01003278:
  fullpath: /g/data/access/payu/access-esm/input/pre-industrial/atmosphere/stasets/X01003278
  hashes:
    binhash: ba5c1b3908374514ff3118300dc9142a
    md5: 032190f23c926eb47199da6e1f054bf1
work/atmosphere/INPUT/stasets/X01003279:
  fullpath: /g/data/access/payu/access-esm/input/pre-industrial/atmosphere/stasets/X01003279
  hashes:
    binhash: 750706183ec07d2b7c025b9e34c042b9
    md5: 120694f3d078b9ade033b56217e9ed85
work/atmosphere/INPUT/stasets/X01003280:
  fullpath: /g/data/access/payu/access-esm/input/pre-industrial/atmosphere/stasets/X01003280
  hashes:
    binhash: 61e9175373ae5b64e4d1919d2395ccbd
    md5: 61afb6eb4e76efb2171c56d02742e9ad
work/atmosphere/INPUT/stasets/X01003281:
  fullpath: /g/data/access/payu/access-esm/input/pre-industrial/atmosphere/stasets/X01003281
  hashes:
    binhash: da9064719c9433460454afacb71ca8d0
    md5: d8cced93214dd8e84c0c9d06259412ab
work/atmosphere/INPUT/stasets/X01003286:
  fullpath: /g/data/access/payu/access-esm/input/pre-industrial/atmosphere/stasets/X01003286
  hashes:
    binhash: 97fd89e81f26f8f7a0c1a850e06c7884
    md5: 062ab130605e4771a89b2a300a6154bf
work/atmosphere/INPUT/stasets/X01005207:
  fullpath: /g/data/access/payu/access-esm/input/pre-industrial/atmosphere/stasets/X01005207
  hashes:
    binhash: 14e3b782aa9d7783e477a33b49221886
    md5: 3d1ccb47257c379b909e8d6098ab95a0
work/atmosphere/INPUT/stasets/X01005208:
  fullpath: /g/data/access/payu/access-esm/input/pre-industrial/atmosphere/stasets/X01005208
  hashes:
    binhash: 3eedbfef9f6a72949516b85a8758a777
    md5: 8685052394200b839f115a667e7890ff
work/atmosphere/INPUT/stasets/X01005222:
  fullpath: /g/data/access/payu/access-esm/input/pre-industrial/atmosphere/stasets/X01005222
  hashes:
    binhash: 490a886ba428213a47d8221d36cf06e9
    md5: 3edd8e46166dbed4102c329991a7a497
work/atmosphere/INPUT/stasets/X01005223:
  fullpath: /g/data/access/payu/access-esm/input/pre-industrial/atmosphere/stasets/X01005223
  hashes:
    binhash: 1bab12d4f494d342afef7b2e5e51f50d
    md5: 4633fea316272fd71cd823881d100c14
work/atmosphere/INPUT/stasets/X01010206:
  fullpath: /g/data/access/payu/access-esm/input/pre-industrial/atmosphere/stasets/X01010206
  hashes:
    binhash: 5c51a194f6aff3c0bfb761305f1b57c0
    md5: 7d5e82e70a2f3936743eb957462d41aa
work/atmosphere/INPUT/sulpc_oxidants_N96_L38:
  fullpath: /g/data/access/payu/access-esm/input/pre-industrial/atmosphere/sulpc_oxidants_N96_L38
  hashes:
    binhash: 4edf15d33d8c6141783b3839e67762d6
    md5: 7c42d1faf74b2b9f6819f2349a8d0d25
work/atmosphere/INPUT/vertlevs_G3:
  fullpath: /g/data/access/payu/access-esm/input/pre-industrial/atmosphere/vertlevs_G3
  hashes:
    binhash: f3f8df2649679869cf7a543e659b6782
    md5: 58ca02de69b16bd59771c81e06c4c21a
work/atmosphere/INPUT/volcts_18502000ave.dat:
  fullpath: /g/data/access/payu/access-esm/input/pre-industrial/atmosphere/volcts_18502000ave.dat
  hashes:
    binhash: c7862f8b76a43ae07cbb471c59051d46
    md5: 47bd369c750be55d706ab60c78bc7aee
work/coupler/areas.nc:
  fullpath: /g/data/access/payu/access-esm/input/pre-industrial/coupler/areas.nc
  hashes:
    binhash: 21cae1a43f7d3e6eb774ac420d0b182b
    md5: 1aac9e2f82d96176f7b87ba1efc8784e
work/coupler/cf_name_table.txt:
  fullpath: /g/data/access/payu/access-esm/input/pre-industrial/coupler/cf_name_table.txt
  hashes:
    binhash: a0cc87db3a4ac852c87412db6b4ad252
    md5: 74333d6fa3153ac294a74a506792375c
work/coupler/grids.nc:
  fullpath: /g/data/access/payu/access-esm/input/pre-industrial/coupler/grids.nc
  hashes:
    binhash: 097cf63ad3cd82cc20aa0baa5364f952
    md5: 2348de62f5fe4d55ec849f79e5d027fd
work/coupler/masks.nc:
  fullpath: /g/data/access/payu/access-esm/input/pre-industrial/coupler/masks.nc
  hashes:
    binhash: c6d82f6152364d083b0870d17718fbbc
    md5: 0a12503901fd3d595bc25b5d3008f9d3
work/coupler/rmp_cice_to_um1t_CONSERV_FRACNNEI.nc:
  fullpath: /g/data/access/payu/access-esm/input/pre-industrial/coupler/rmp_cice_to_um1t_CONSERV_FRACNNEI.nc
  hashes:
    binhash: a18e25b2be0c9b5f54275749e15f777d
    md5: a8129dba5b3a7f70a5bc2fbf7f0e4f68
work/coupler/rmp_cice_to_um1u_CONSERV_FRACNNEI.nc:
  fullpath: /g/data/access/payu/access-esm/input/pre-industrial/coupler/rmp_cice_to_um1u_CONSERV_FRACNNEI.nc
  hashes:
    binhash: 6cfe2d688759dc7edda7643c9f6730c2
    md5: 6fc856e7c2014e20903a01cdd61f4f2c
work/coupler/rmp_cice_to_um1v_CONSERV_FRACNNEI.nc:
  fullpath: /g/data/access/payu/access-esm/input/pre-industrial/coupler/rmp_cice_to_um1v_CONSERV_FRACNNEI.nc
  hashes:
    binhash: 0f259452f418298d6dfb7b7047616c72
    md5: a2a7d940a9eaab59ec8fa49154116a64
work/coupler/rmp_um1t_to_cice_CONSERV_DESTAREA.nc:
  fullpath: /g/data/access/payu/access-esm/input/pre-industrial/coupler/rmp_um1t_to_cice_CONSERV_DESTAREA.nc
  hashes:
    binhash: 3e40a993ca21b7d8f0431307a92dee93
    md5: 25be6489585df07097d4b6009bf23ec2
work/coupler/rmp_um1t_to_cice_CONSERV_FRACNNEI.nc:
  fullpath: /g/data/access/payu/access-esm/input/pre-industrial/coupler/rmp_um1t_to_cice_CONSERV_FRACNNEI.nc
  hashes:
    binhash: 7d0c9d98e764d4c27a134d9a3577b466
    md5: 269086623444b48d0cd481e69d4bdc5f
work/coupler/rmp_um1u_to_cice_CONSERV_FRACNNEI.nc:
  fullpath: /g/data/access/payu/access-esm/input/pre-industrial/coupler/rmp_um1u_to_cice_CONSERV_FRACNNEI.nc
  hashes:
    binhash: 83a4e000c728a5312bc9265838ee4185
    md5: 58ea836bf1e12d5fc21460763b02548f
work/coupler/rmp_um1v_to_cice_CONSERV_FRACNNEI.nc:
  fullpath: /g/data/access/payu/access-esm/input/pre-industrial/coupler/rmp_um1v_to_cice_CONSERV_FRACNNEI.nc
  hashes:
    binhash: 020d985b81c6c7a6e2e44b8e89ee2d43
    md5: 3bf9569f34b657f2ecab8ef5c93e7659
work/ice/INPUT/grid.nc:
  fullpath: /g/data/access/payu/access-esm/input/pre-industrial/ice/grid.nc
  hashes:
    binhash: c0e1fc33b9cf16ed53b32c77af275e18
    md5: 1213e346055ee073fe33dc12578d99c6
work/ice/INPUT/kmt.nc:
  fullpath: /g/data/access/payu/access-esm/input/pre-industrial/ice/kmt.nc
  hashes:
    binhash: 15455ece12e3ea26f56f0272d1f2a6f2
    md5: 2bde88b9e44c46aecf2ba2dff188d1ac
work/ice/INPUT/monthly_sstsss.nc:
  fullpath: /g/data/access/payu/access-esm/input/pre-industrial/ice/monthly_sstsss.nc
  hashes:
    binhash: 2128e978f4ff9631d31687d3400e38f9
    md5: 323d4c605f83f4d7d3126da70153c2ed
work/ocean/INPUT/basin_mask.nc:
  fullpath: /g/data/access/payu/access-esm/input/pre-industrial/ocean/common/basin_mask.nc
  hashes:
    binhash: 9c273f0ed87133742865d04ee655eaa8
    md5: 20fd8740f24ca95c7c086343077e9c0d
work/ocean/INPUT/bgc_param.nc:
  fullpath: /g/data/access/payu/access-esm/input/pre-industrial/ocean/pre-industrial/bgc_param.nc
  hashes:
    binhash: 2ab0de4b6a7453d14376cc2c4a4615c5
    md5: 7162c91ab9399c7a225fcb03593843ee
work/ocean/INPUT/cfc_auscom.nc:
  fullpath: /g/data/access/payu/access-esm/input/pre-industrial/ocean/pre-industrial/cfc_auscom.nc
  hashes:
    binhash: 075ccc190b2467f6d33d0f77a3728fd5
    md5: 38660c8a5de3e3b63d2ae7ba5020d515
work/ocean/INPUT/co2_obs.nc:
  fullpath: /g/data/access/payu/access-esm/input/pre-industrial/ocean/pre-industrial/co2_obs.nc
  hashes:
    binhash: ae85b0b6712c9faf6973d1b004286272
    md5: bfc3011737ab384d770b937b269e50fc
work/ocean/INPUT/dust.nc:
  fullpath: /g/data/access/payu/access-esm/input/pre-industrial/ocean/pre-industrial/dust.nc
  hashes:
    binhash: 374b73916dc4f04f36a1bc4316fd8071
    md5: bfbbea8ac46a932d0ec8631afbfc2ae2
work/ocean/INPUT/geothermal_heating.nc:
  fullpath: /g/data/access/payu/access-esm/input/pre-industrial/ocean/common/geothermal_heating.nc
  hashes:
    binhash: 2314e8fcafc7279c2ebecac7f55d5a1e
    md5: 381cb231d8d059576adca0c2bea9c030
work/ocean/INPUT/grid_spec.nc:
  fullpath: /g/data/access/payu/access-esm/input/pre-industrial/ocean/common/grid_spec.nc
  hashes:
    binhash: 00361652bc2eb575ccaa26a2a49323e3
    md5: b9adc1e552201aa3abc6efb72786ec93
work/ocean/INPUT/ocmip2_abiotic_c14_atm_hist_om3_bc-1-9999.nc:
  fullpath: /g/data/access/payu/access-esm/input/pre-industrial/ocean/pre-industrial/ocmip2_abiotic_c14_atm_hist_om3_bc-1-9999.nc
  hashes:
    binhash: 2b8ebb65bc9a0da54478293e7e000b56
    md5: e91a04235ab63ef060d0c6e350ed9581
work/ocean/INPUT/ocmip2_fice_monthly_om1p5_bc.nc:
  fullpath: /g/data/access/payu/access-esm/input/pre-industrial/ocean/pre-industrial/ocmip2_fice_monthly_om1p5_bc.nc
  hashes:
    binhash: 73881ad2628a5608e35773732f23f38b
    md5: c0ed75eef44962dbe6fc9f61dbd228a9
work/ocean/INPUT/ocmip2_press_monthly_om1p5_bc.nc:
  fullpath: /g/data/access/payu/access-esm/input/pre-industrial/ocean/pre-industrial/ocmip2_press_monthly_om1p5_bc.nc
  hashes:
    binhash: 1a034ba81daf08808e82762a0d22eef3
    md5: 2e71cbb78c052e06e3df20f862928da2
work/ocean/INPUT/ocmip2_siple_co2_atm_am2_bc-1-9999.nc:
  fullpath: /g/data/access/payu/access-esm/input/pre-industrial/ocean/pre-industrial/ocmip2_siple_co2_atm_am2_bc-1-9999.nc
  hashes:
    binhash: 49878db364d6b7d04be26aa19875af97
    md5: bf1db4228eeacb676da968073b8c5848
work/ocean/INPUT/ocmip2_xkw_monthly_om1p5_bc.nc:
  fullpath: /g/data/access/payu/access-esm/input/pre-industrial/ocean/pre-industrial/ocmip2_xkw_monthly_om1p5_bc.nc
  hashes:
    binhash: fa7e5087f8421bed7d69124f94975d91
    md5: 348a035bed83e280bb0a1de0066947fc
work/ocean/INPUT/roughness_amp.nc:
  fullpath: /g/data/access/payu/access-esm/input/pre-industrial/ocean/common/roughness_amp.nc
  hashes:
    binhash: 6b1194d04fda9027a0f0928e39e8be1c
    md5: 185dadeb53da2de75b47c53fd7085f89
work/ocean/INPUT/ssw_atten_depth.nc:
  fullpath: /g/data/access/payu/access-esm/input/pre-industrial/ocean/common/ssw_atten_depth.nc
  hashes:
    binhash: 6a4a2c066c9c7cbc34035bfcd5d855d6
    md5: 3e88b51db135788aa4348d58cbeabfad
work/ocean/INPUT/tideamp.nc:
  fullpath: /g/data/access/payu/access-esm/input/pre-industrial/ocean/common/tideamp.nc
  hashes:
    binhash: 9e635a2039b0c2f39e2c131e03f5527b
    md5: b2840af757d9b7b40207f33f1fc84c5c
